<a href="https://colab.research.google.com/github/HYMOT/sikyungKim_2022231114/blob/main/python_example_11.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
!pip install numpy

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


In [5]:
import numpy as np

a = np.arange(6)
a2 = a[np.newaxis, :]
a2.shape

(1, 6)

In [6]:
type(a)

numpy.ndarray

In [7]:
a

array([0, 1, 2, 3, 4, 5])

In [8]:
a[0]

0

In [9]:
a[:]

array([0, 1, 2, 3, 4, 5])

In [10]:
a2 = a[np.newaxis, :]

In [11]:
a2.shape

(1, 6)

In [12]:
a.shape

(6,)

In [14]:
a = np.array([1,2,3,4,5,6])
a = np.array([[2,3,4,5], [5,6,7,8], [2,3,4,6]])

In [15]:
print(a[0])

[2 3 4 5]


In [16]:
a

array([[2, 3, 4, 5],
       [5, 6, 7, 8],
       [2, 3, 4, 6]])

In [17]:
a[0,1]

3

In [18]:
np.empty(2)

array([-5.73021895e-300,  2.25115083e-316])

In [19]:
np.arange(2, 9, 2)

array([2, 4, 6, 8])

In [20]:
np.linspace(0, 10, num=5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [25]:
b = np.ones(2, dtype=np.int64)
print(b)

[1 1]


In [27]:
arr = np.array([2,1,4,6,7,8,3,5])
arr

array([2, 1, 4, 6, 7, 8, 3, 5])

In [29]:
arr = np.sort(arr)

array([1, 2, 3, 4, 5, 6, 7, 8])

In [30]:
a = np.array([1,2,3,4])
b = np.array([5,6,7,8])

In [33]:
np.concatenate((a,b))

array([1, 2, 3, 4, 5, 6, 7, 8])

In [34]:
x = np.array([[1,2],[3,4]])
y = np.array([[5,6]])

In [38]:
np.concatenate((x,y), axis = 0)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [40]:
array_example = np.array([[[0,1,2,3],[4,5,6,7]],[[0,1,2,3],[4,5,6,7]], [[0,1,2,3],[4,5,6,7]]])
array_example

array([[[0, 1, 2, 3],
        [4, 5, 6, 7]],

       [[0, 1, 2, 3],
        [4, 5, 6, 7]],

       [[0, 1, 2, 3],
        [4, 5, 6, 7]]])

In [41]:
array_example.ndim

3

In [42]:
array_example.size

24

In [43]:
array_example.shape

(3, 2, 4)

In [44]:
a = np.arange(6)

In [45]:
a.reshape(1,6)

array([[0, 1, 2, 3, 4, 5]])

In [46]:
a.reshape(2,3)

array([[0, 1, 2],
       [3, 4, 5]])

In [47]:
np.reshape(a, newshape=(1,6), order='C')

array([[0, 1, 2, 3, 4, 5]])

In [48]:
a = [[1,2,3], [4,5,6]]

In [49]:
a

[[1, 2, 3], [4, 5, 6]]

In [56]:
a[0][1]

2

In [58]:
a = np.array([1,2,3,4,5,6])

In [59]:
a2 = a[np.newaxis, :]

In [60]:
a2.shape

(1, 6)

In [61]:
row_vector = a[np.newaxis, :]

In [62]:
row_vector.shape

(1, 6)

In [63]:
a[:, np.newaxis]

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

In [ ]:
data = np.array([1,2,3])

In [68]:
data

array([1, 2, 3])

In [69]:
data[0:2]

array([1, 2])

In [70]:
data[1:]

array([2, 3])

In [71]:
data[-2:]

array([2, 3])

In [72]:
a = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])

In [73]:
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [74]:
a.shape

(3, 4)

In [75]:
a < 5

array([[ True,  True,  True,  True],
       [False, False, False, False],
       [False, False, False, False]])

In [76]:
b = 2

In [77]:
if b > 5:
  print("에구 너무 큰데요")
else:
  print("좋아요")

좋아요


In [78]:
b > 5 

False

In [79]:
a[a<5]

array([1, 2, 3, 4])

In [81]:
a[a>=5]

array([ 5,  6,  7,  8,  9, 10, 11, 12])

In [83]:
a[a % 2 ==0]

array([ 2,  4,  6,  8, 10, 12])

In [84]:
a[(a >2)& (a <11)]

array([ 3,  4,  5,  6,  7,  8,  9, 10])

In [85]:
a[(a > 5)| (a ==5)]

array([ 5,  6,  7,  8,  9, 10, 11, 12])

In [87]:
b = np.nonzero(a < 5)

In [88]:
b

(array([0, 0, 0, 0]), array([0, 1, 2, 3]))

In [90]:
list_of_coordinates = list(zip(b[0], b[1]))

In [91]:
list_of_coordinates

[(0, 0), (0, 1), (0, 2), (0, 3)]

In [92]:
for coord in list_of_coordinates:
  print(coord)

(0, 0)
(0, 1)
(0, 2)
(0, 3)


In [93]:
a = np.array([1,2,3,4,5,6,7,8,9,10])

In [95]:
arr1 = a[3:8]
arr1

array([4, 5, 6, 7, 8])

In [96]:
a1 = np.array([[1,1],
               [2,2]])

In [97]:
a2 = np.array([[1,1],
               [2,2]])     

In [98]:
a1

array([[1, 1],
       [2, 2]])

In [99]:
a2

array([[1, 1],
       [2, 2]])

In [100]:
np.concatenate((a1, a2), axis=1)

array([[1, 1, 1, 1],
       [2, 2, 2, 2]])

In [103]:
a = np.arange(1, 15)

In [104]:
a.reshape(2,7)

array([[ 1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14]])

In [105]:
np.arange(1,15).reshape(2,7)

array([[ 1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14]])

In [107]:
x = np.arange(1, 25).reshape(2, 12)

In [109]:
np.hsplit(x, 3)[0]

array([[ 1,  2,  3,  4],
       [13, 14, 15, 16]])

In [110]:
np.hsplit(x, (3,4))

[array([[ 1,  2,  3],
        [13, 14, 15]]),
 array([[ 4],
        [16]]),
 array([[ 5,  6,  7,  8,  9, 10, 11, 12],
        [17, 18, 19, 20, 21, 22, 23, 24]])]

In [111]:
a = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])

In [112]:
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [114]:
a[2,:]

array([ 9, 10, 11, 12])

In [116]:
b1 = a[0,:]
b1

array([1, 2, 3, 4])

In [119]:
b1[0] = 99

In [120]:
b1

array([99,  2,  3,  4])

In [121]:
a

array([[99,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [122]:
a = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])

In [123]:
b1 = a[0,:].copy()

In [124]:
b1

array([1, 2, 3, 4])

In [126]:
b1[0] = 99
b1

array([99,  2,  3,  4])

In [127]:
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [128]:
data = np.array([1,2])

In [129]:
ones = np.ones(2, dtype=int)

In [130]:
data 

array([1, 2])

In [131]:
ones

array([1, 1])

In [132]:
data + ones

array([2, 3])

In [133]:
a.sum()

78

In [136]:
b = [1,22,3,4]
len(b)

4

In [138]:
b.sort()
b

[1, 3, 4, 22]

In [140]:
b = np.array([[1,1], [2,2]])
b.sum(axis =0)

array([3, 3])

In [142]:
b

array([[1, 1],
       [2, 2]])

In [144]:
b.sum(axis = 1)

array([2, 4])

In [145]:
a.max()

12

In [146]:
a.min()

1

In [148]:
b = np.array([[1,4], [2,7]])
b

array([[1, 4],
       [2, 7]])

In [149]:
b.min(axis =0)

array([1, 4])

In [150]:
a = np.array([1,2,3,4])
data = np.array([[1,2],[3,4],[5,6]])
data[0,1]

2

In [151]:
data

array([[1, 2],
       [3, 4],
       [5, 6]])

In [152]:
data[1:3]

array([[3, 4],
       [5, 6]])

In [154]:
data[0:2,0]

array([1, 3])

In [155]:
data.max() 

6

In [157]:
data = np.array([[1,2],[3,4],[5,6]])
ones_row = np.array([[1,1]])
data + ones_row

array([[2, 3],
       [4, 5],
       [6, 7]])

In [158]:
a = np.array([11, 11, 12, 13, 14, 15, 16, 17, 12, 13, 11, 14, 18, 19, 20])

In [162]:
np.unique(a, return_index=True)

(array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20]),
 array([ 0,  2,  3,  4,  5,  6,  7, 12, 13, 14]))

In [164]:
a_2d = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12], [1, 2, 3, 4]])
unique_values = np.unique(a_2d)
print(unique_values)

[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [165]:
unique_rows = np.unique(a_2d, axis=0)
print(unique_rows)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [166]:
unique_rows, indices, occurrence_count = np.unique(
     a_2d, axis=0, return_counts=True, return_index=True)
print(unique_rows)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [168]:
data.reshape(2, 3)


array([[1, 2, 3],
       [4, 5, 6]])

In [169]:
data.reshape(3, 2)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [171]:
arr = np.arange(6).reshape((2, 3))
arr

array([[0, 1, 2],
       [3, 4, 5]])

In [172]:
arr.transpose()

array([[0, 3],
       [1, 4],
       [2, 5]])

In [173]:
arr.T

array([[0, 3],
       [1, 4],
       [2, 5]])

In [175]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])
reversed_arr = np.flip(arr)

In [176]:
print('Reversed Array: ', reversed_arr)

Reversed Array:  [8 7 6 5 4 3 2 1]


In [177]:
arr_2d = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

In [178]:
reversed_arr = np.flip(arr_2d)
print(reversed_arr)

[[12 11 10  9]
 [ 8  7  6  5]
 [ 4  3  2  1]]


In [179]:
arr_2d[:,1] = np.flip(arr_2d[:,1])
print(arr_2d)

[[ 1 10  3  4]
 [ 5  6  7  8]
 [ 9  2 11 12]]


In [180]:
x = np.array([[1 , 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

In [181]:
x.flatten()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [182]:
a1 = x.flatten()
a1[0] = 99
print(x)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [184]:
print(a1)

[99  2  3  4  5  6  7  8  9 10 11 12]


In [185]:
print(a2)

[98  2  3  4  5  6  7  8  9 10 11 12]


In [183]:
a2 = x.ravel()
a2[0] = 98
print(x)

[[98  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
